export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CART_ITEMS_CHANGED = "CART_ITEMS_CHANGED";

export const CHECK_STATUS = "CHECK_STATUS"
