export const GET_PRODUCTS = "GET_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const PRICE_FILTER = "PRICE_FILTER";
export const SELECTED_PRODUCTS = "SELECTED_PRODUCTS";
export const PRODUCT_LIST = "PRODUCT_LIST";
