export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const SORT_TYPE_CHANGED = "SORT_TYPE_CHANGED";
export const SEARCH_TYPE_CHANGED = "SEARCH_TYPE_CHANGED";
export const MODAL_OPEN = "MODAL_OPEN";
export const PRODUCT_SELECTED = "PRODUCT_SELECTED";
export const CATEGORY_VALUE_CHANGED = "CATEGORY_VALUE_CHANGED";
export const CART_PRODUCT_UPDATED = "CART_PRODUCTS_UPDATED";
export const EDIT_MODAL_OPEN = "EDIT_MODAL_OPEN";
